// One-time migration: import the legacy markdown Notes from src/content/note/
// into the `ap_notes` D1 table (see docs/adr/0002-*). Generates an idempotent
// seed SQL file rather than touching the database directly, so it can be
// reviewed and applied with wrangler:
//
//   node scripts/d1/migrate-notes.mjs
//   wrangler d1 execute DATABASE --file=scripts/d1/seed-notes.sql --local   # or --remote
//
// Deterministic: each note's ULID is seeded from its identity, so re-running
// produces the same ids and the ON CONFLICT upsert stays idempotent.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ulid } from "ulid";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const NOTE_DIR = join(ROOT, "src", "content", "note");
const OUT = join(ROOT, "scripts", "d1", "seed-notes.sql");

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

function unquote(value) {
	const v = value.trim();
	if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
		return v.slice(1, -1);
	}
	return v;
}

function parseFrontmatter(block) {
	const fields = {};
	for (const line of block.split(/\r?\n/)) {
		const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
		if (m) fields[m[1]] = unquote(m[2]);
	}
	return fields;
}

// Deterministic PRNG (mulberry32) seeded from a string, so ULID random bits are
// stable per note across regenerations.
function seededPrng(seed) {
	let h = 1779033703 ^ seed.length;
	for (let i = 0; i < seed.length; i++) {
		h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
		h = (h << 13) | (h >>> 19);
	}
	let a = h >>> 0;
	return () => {
		a |= 0;
		a = (a + 0x6d2b79f5) | 0;
		let t = Math.imul(a ^ (a >>> 15), 1 | a);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}

function sqlString(value) {
	if (value === null || value === undefined) return "NULL";
	return `'${String(value).replace(/'/g, "''")}'`;
}

const files = readdirSync(NOTE_DIR)
	.filter((f) => f.endsWith(".md") || f.endsWith(".mdx"))
	.sort();

const rows = files.map((file) => {
	const raw = readFileSync(join(NOTE_DIR, file), "utf8");
	const match = raw.match(FRONTMATTER);
	if (!match) throw new Error(`${file}: missing frontmatter`);
	const fields = parseFrontmatter(match[1]);
	if (!fields.publishDate) throw new Error(`${file}: missing publishDate`);
	const publishDate = new Date(fields.publishDate);
	if (Number.isNaN(publishDate.getTime())) {
		throw new Error(`${file}: invalid publishDate ${fields.publishDate}`);
	}
	const iso = publishDate.toISOString();
	const id = ulid(publishDate.getTime(), seededPrng(`${fields.title ?? file}|${iso}`));
	return {
		id,
		title: fields.title ?? null,
		content: raw.slice(match[0].length),
		summary: fields.description ?? null,
		published_at: iso,
	};
});

const statements = rows.map(
	(r) =>
		"INSERT INTO ap_notes (id, title, content, summary, published_at, updated_at, created_at, source)\n" +
		`VALUES (${sqlString(r.id)}, ${sqlString(r.title)}, ${sqlString(r.content)}, ${sqlString(r.summary)}, ${sqlString(r.published_at)}, ${sqlString(r.published_at)}, ${sqlString(r.published_at)}, 'migration')\n` +
		"ON CONFLICT(id) DO UPDATE SET title=excluded.title, content=excluded.content, summary=excluded.summary, published_at=excluded.published_at, updated_at=excluded.updated_at, source=excluded.source;",
);

const header =
	"-- Generated by scripts/d1/migrate-notes.mjs — legacy markdown Notes seeded into ap_notes.\n" +
	"-- Regenerate with: node scripts/d1/migrate-notes.mjs\n\n";

writeFileSync(OUT, `${header + statements.join("\n\n")}\n`);
console.log(`Wrote ${rows.length} note(s) to ${OUT}`);
for (const r of rows) console.log(`  ${r.id}  ${r.published_at}  ${r.title ?? "(untitled)"}`);
